"""empty message

Revision ID: 6020f208b853
Revises: 2aba5f7bd3e4
Create Date: 2016-02-03 16:00:47.069502

"""

# revision identifiers, used by Alembic.
revision = '6020f208b853'
down_revision = '2aba5f7bd3e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='pins')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'pins', ['name'], unique=True)
    ### end Alembic commands ###
