"""empty message

Revision ID: 611f62f459ae
Revises: e341a849a6a4
Create Date: 2016-02-02 16:38:18.652284

"""

# revision identifiers, used by Alembic.
revision = '611f62f459ae'
down_revision = 'e341a849a6a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('type', sa.String(length=255), nullable=True))
    op.add_column('pins', sa.Column('status', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'pins', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pins', type_='unique')
    op.drop_column('pins', 'status')
    op.drop_column('devices', 'type')
    ### end Alembic commands ###
