"""empty message

Revision ID: 764fbf814098
Revises: 6020f208b853
Create Date: 2016-02-04 11:48:56.833214

"""

# revision identifiers, used by Alembic.
revision = '764fbf814098'
down_revision = '6020f208b853'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('uuid', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'uuid')
    ### end Alembic commands ###
